
[tool.ruff]
line-length = 120

[tool.ruff.lint]
logger-objects = ["loguru.logger"]
select = ["ALL"]
ignore = [
	"COM812", # missing-trailing-comma
	"T20", # flake8-print
	"ERA", # eradicate
]

[tool.ruff.lint.pydocstyle]
convention = "google"
